version: '3.8'

services:
  postgres:
    container_name: pg_db
    image: postgres:16
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: leaderboard
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  app:
    container_name: leaderboard_app
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    volumes:
      - app_data:/app/logs

volumes:
  postgres_data:
  app_data: